/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.9.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as databaseTypes from "../databaseTypes.js";
import type * as diagrams from "../diagrams.js";
import type * as entities from "../entities.js";
import type * as helpers_UserQuery from "../helpers/UserQuery.js";
import type * as rowTypes from "../rowTypes.js";
import type * as rows from "../rows.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  databaseTypes: typeof databaseTypes;
  diagrams: typeof diagrams;
  entities: typeof entities;
  "helpers/UserQuery": typeof helpers_UserQuery;
  rowTypes: typeof rowTypes;
  rows: typeof rows;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
