// "use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/ThemeProvider";
import { cn } from "@/lib/utils";
import { ConvexClientProvider } from "@/providers/convex.provider";
import { Navbar } from "@/components/Nabar";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "dark:bg-[#1f1f1f]")}>
        <ConvexClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            storageKey="pistachio-theme"
          >
            <Toaster />
            <Navbar />
            <main className="h-full pt-40">{children}</main>
          </ThemeProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
